apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: isol8
rules:
- apiGroups: [""]
  resources: ["services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: isol8
subjects:
- kind: ServiceAccount
  name: {{ include "isol8.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: isol8
  apiGroup: rbac.authorization.k8s.io