name: Build Container Image

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Github - Checkout
        uses: actions/checkout@v2

      - name: Docker - Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Variables - Setup
        id: set-variables
        run: |
          echo "REPOSITORY=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
          echo "VERSION=$(yq -r .version ./deploy/Chart.yaml)" >> "$GITHUB_OUTPUT"    

      - name: Docker - Build
        run: docker build -t ghcr.io/${{ steps.set-variables.outputs.REPOSITORY }}:latest -t ghcr.io/${{ steps.set-variables.outputs.REPOSITORY }}:${{ github.sha }} ./src/Isol8

      - name: GHCR - Login
        uses: docker/login-action@v1
        if: github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Docker - Push
        if: github.event_name == 'push'
        run: |
          docker push ghcr.io/${{ steps.set-variables.outputs.REPOSITORY }}/isol8:latest
          docker push ghcr.io/${{ steps.set-variables.outputs.REPOSITORY }}/isol8:${{ github.sha }}
