name: Build Container Image

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Github - Checkout
        uses: actions/checkout@v2

      - name: Docker - Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker - Build
        run: docker build -t ghcr.io/${{ github.repository }}/isol8:latest -t ghcr.io/${{ github.repository }}/isol8:${{ github.sha }} ./src/Isol8

      - name: GHCR - Login
        uses: docker/login-action@v1
        if: github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Docker - Push
        if: github.event_name == 'push'
        run: docker push ghcr.io/${{ github.repository }}/isol8:latest
